steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        export GOOGLE_APPLICATION_CREDENTIALS=/workspace/secret-manager.json
        gcloud secrets versions access latest --secret=secret-manager > $$GOOGLE_APPLICATION_CREDENTIALS
    env:
      - GOOGLE_APPLICATION_CREDENTIALS=/workspace/secret-manager.json
      - TF_VAR_project_id=swetha-sceg
      - TF_VAR_region=us-central1
  - name: 'hashicorp/terraform:latest'
    args:
      - 'init'
    env:
      - GOOGLE_APPLICATION_CREDENTIALS=/workspace/secret-manager.json
      - TF_VAR_project_id=swetha-sceg
      - TF_VAR_region=us-central1
 
  - name: 'hashicorp/terraform:latest'
    args:
      - 'plan'
      - '-out=tfplan'
    env:
      - GOOGLE_APPLICATION_CREDENTIALS=/workspace/secret-manager.json
      - TF_VAR_project_id=swetha-sceg
      - TF_VAR_region=us-central1
 
  - name: 'hashicorp/terraform:latest'
    args:
      - 'apply'
      - '-auto-approve'
      - 'tfplan'
    env:
      - GOOGLE_APPLICATION_CREDENTIALS=/workspace/secret-manager.json
      - TF_VAR_project_id=swetha-sceg
      - TF_VAR_region=us-central1
 